[parity]
chain = "demo-spec_poa.json"
base_path = "parity3"
[network]
port = 30303
reserved_peers = "bootnodes.txt"
[rpc]
port = 8543
apis = ["all"]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
[websockets]
port = 8453
[ipc]
disable = true
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x9ab4b03926f7c582d8db1a0cc64c3cafcf7a38c6"
reseal_on_txs = "none"
force_sealing = true
